/* ═══════════════════════════════════════════════════════════════════════════
   Rewrites the two brand preset sheets into ONE scoped stylesheet for the
   Storybook workshop: .storybook/brands.generated.css

   WHY THIS EXISTS. @devopsnext/starterkit-theme publishes each brand as a
   standalone sheet that owns `:root`. Loading both at once is meaningless —
   whichever comes last wins the whole document, forever. To offer the brand as
   a toolbar axis, each preset has to become addressable instead of global:

       :root                            ->  [data-brand="think"]
       [data-mui-color-scheme="light"]  ->  [data-brand="think"][data-mui-color-scheme="light"]

   That rewrite is all this script does. Values are copied verbatim; nothing is
   recomputed, so the workshop cannot drift into showing a colour the theme
   engine would not produce.

   WHY IT IS VENDORED AND COMMITTED. The theme package is not on npm, and any
   checkout that does not also have the sibling `starterkit-theme` repo beside
   it cannot resolve a `file:../starterkit-theme` devDependency — it would fail
   `pnpm install --frozen-lockfile` outright. So the output is committed, and
   `--check` is a LOCAL gate: it needs that sibling checkout to have anything
   to compare against. Contrast `sync:tokens:check`, which reads a public CDN
   URL and can therefore run anywhere.

   The output is workshop-only. It is not in package.json `files`, and the
   published component still ships zero brand dependency: styles.css keeps
   winning by CSS fallback, exactly as before.

     node scripts/gen-brands.mjs                 rewrite
     node scripts/gen-brands.mjs --check         exit 1 if stale (local gate)
     node scripts/gen-brands.mjs --source=<dir>  read presets from elsewhere
   ═══════════════════════════════════════════════════════════════════════════ */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, relative, sep } from "node:path";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const TARGET = join(ROOT, ".storybook", "brands.generated.css");
const DEFAULT_SOURCE = join(ROOT, "..", "starterkit-theme", "presets");

/* Hand-synced with PRESET_IDS in starterkit-theme/src/presets/index.ts, the
   same way that package's own schema.json hand-syncs its `preset` enum. Two
   brands is the whole roster; a third one lands here and in manager.tsx. */
const BRANDS = [
  { id: "think", label: "Think" },
  { id: "elemetrik", label: "Elemetrik" },
];

/* The preset sheets publish their light scheme under MUI's attribute only.
   styles.css and the Storybook decorator also honour `data-theme`, so the
   scoped rule declares both — the same pair sync-tokens.mjs emits. */
const LIGHT_SELECTOR = '[data-mui-color-scheme="light"]';

const sourceArg = process.argv.find((arg) => arg.startsWith("--source="));
const SOURCE = sourceArg ? sourceArg.slice("--source=".length) : DEFAULT_SOURCE;

const START = "/* @brands:start — generated by scripts/gen-brands.mjs, do not edit */";
const END = "/* @brands:end */";

/** Body of the first top-level `selector { … }`, by brace matching. */
function ruleBody(css, selector) {
  const at = css.indexOf(selector + " {");
  if (at === -1) throw new Error(`selector not found in preset sheet: ${selector}`);
  const open = css.indexOf("{", at);
  let depth = 0;
  for (let i = open; i < css.length; i++) {
    if (css[i] === "{") depth++;
    else if (css[i] === "}" && --depth === 0) return css.slice(open + 1, i);
  }
  throw new Error(`unterminated rule: ${selector}`);
}

/**
 * Every declaration in source order, custom properties AND plain ones.
 *
 * Unlike sync-tokens.mjs's `customProps`, `color-scheme: light` is KEPT: it is
 * the last line of every preset's light block and it is load-bearing — it is
 * what tells the UA to paint light scrollbars and form controls. Dropping it
 * would leave the workshop with light tokens and dark native chrome.
 */
function declarations(body) {
  const out = [];
  let depth = 0;
  let buf = "";
  const flush = () => {
    const decl = buf.replace(/\/\*[\s\S]*?\*\//g, "").trim();
    buf = "";
    const split = decl.indexOf(":");
    if (split === -1) return;
    out.push([decl.slice(0, split).trim(), decl.slice(split + 1).trim().replace(/\s+/g, " ")]);
  };
  for (const ch of body) {
    if (ch === "(") depth++;
    else if (ch === ")") depth--;
    if (ch === ";" && depth === 0) flush();
    else buf += ch;
  }
  flush();
  return out;
}

const emit = (decls, indent = "  ") =>
  decls.map(([name, value]) => `${indent}${name}: ${value};`).join("\n");

const brands = BRANDS.map(({ id, label }) => {
  const file = join(SOURCE, `${id}.css`);
  if (!existsSync(file)) {
    throw new Error(
      `preset sheet missing: ${file}\n` +
        "Point --source= at a checkout of starterkit-theme's presets/ directory.",
    );
  }
  const sheet = readFileSync(file, "utf8");
  const dark = declarations(ruleBody(sheet, ":root"));
  const light = declarations(ruleBody(sheet, LIGHT_SELECTOR));

  /* A preset that suddenly resolves to a handful of tokens means the upstream
     serializer changed shape, not that the brand got simpler. Fail rather than
     commit a sheet that silently under-defines the workshop. */
  if (dark.length < 100) throw new Error(`${id}: :root has only ${dark.length} declarations`);
  if (light.length < 40) throw new Error(`${id}: light block has only ${light.length} declarations`);

  const version = dark.find(([name]) => name === "--tokens-version")?.[1];
  const stamped = dark.find(([name]) => name === "--tokens-brand")?.[1];
  if (stamped !== `"${id}"`) throw new Error(`${id}: sheet stamps --tokens-brand: ${stamped}`);

  return { id, label, dark, light, version };
});

const versions = [...new Set(brands.map((b) => b.version))];
if (versions.length !== 1) {
  throw new Error(`presets disagree on --tokens-version: ${versions.join(", ")}`);
}

const sourceLabel = relative(ROOT, SOURCE).split(sep).join("/") || SOURCE;

const blocks = brands
  .map(
    ({ id, label, dark, light }) => `/* ${label} — ${dark.length} tokens, ${light.length} in light. */
[data-brand="${id}"] {
${emit(dark)}
}

[data-brand="${id}"]${LIGHT_SELECTOR},
[data-brand="${id}"][data-theme="light"] {
${emit(light)}
}`,
  )
  .join("\n\n");

const block = `${START}
/* Source: ${sourceLabel}/<brand>.css @ --tokens-version ${versions[0]}
   Regenerate with \`pnpm gen:brands\`; \`pnpm gen:brands:check\` reports drift.

   Each preset's \`:root\` becomes \`[data-brand="<id>"]\`, and its light block
   becomes that same attribute PLUS the scheme attribute — a compound selector
   on ONE element, not a descendant pair. So whatever carries data-brand must
   carry the scheme attribute too. In the workshop that is <html> (see the
   decorator in .storybook/preview.tsx); in the BrandComparison story it is
   each column wrapper, which is why those wrappers restate the scheme.

   Specificity: the light rule is (0,2,0) against the dark rule's (0,1,0), so
   light wins whenever it matches, without !important or a source-order trick.

   These tokens are what .ic-card's \`var(--x, <vendored default>)\` aliases read.
   The defaults baked into styles.css ARE the Think values, so selecting Think
   is indistinguishable from selecting no brand at all — Elemetrik is the half
   of this file that actually changes anything. */

${blocks}
${END}
`;

const current = existsSync(TARGET) ? readFileSync(TARGET, "utf8") : "";
const summary = brands.map((b) => `${b.id} (${b.dark.length}/${b.light.length})`).join(", ");

if (process.argv.includes("--check")) {
  if (block !== current) {
    console.error(".storybook/brands.generated.css is stale — run `pnpm gen:brands`");
    process.exit(1);
  }
  console.log(`brands up to date: ${summary}`);
} else {
  writeFileSync(TARGET, block);
  console.log(`generated ${summary} from ${sourceLabel} @ ${versions[0]}`);
}
