/* ═══════════════════════════════════════════════════════════════════════════
   Regenerates the token-alias block inside styles.css from the Obsidian sheet.

   THE CONTRACT: the remote sheet is primary, styles.css is the backup.

   That is enforced without `@layer` and without declaring `:root`. Every token
   the component consumes is aliased once, on `.ic-card` itself, as

       --ic-t-glass-bg: var(--glass-bg, rgba(255, 255, 255, 0.035));

   so the host's value wins whenever it exists — a CSS fallback applies only to
   an absent custom property — and the vendored copy renders the component when
   it does not. Nothing is written to the host document, which is the part a
   layered `:root` block could not offer: layered or not, `:root { --border: … }`
   still hands every other component on the page a --border.

   Vendored defaults are resolved transitively, so a default never depends on a
   token the host might not have:

       --gradient-cobalt: linear-gradient(145deg, var(--cobalt-light), …)
     → var(--gradient-cobalt, linear-gradient(145deg,
           var(--cobalt-light, #37A3FE), var(--cobalt-deep, #006ACC)))

   The seed set is scraped from styles.css itself — every `--ic-t-x` a rule
   mentions. Use a new token and the next run vendors it; stop using one and it
   disappears. No hand-maintained list, no drift.

     node scripts/sync-tokens.mjs                 rewrite the block
     node scripts/sync-tokens.mjs --check         exit 1 if stale (CI)
     node scripts/sync-tokens.mjs --source=<path> read a local sheet instead

   `--source` exists for offline work and for regenerating against a checkout of
   the design system before it is published to the CDN. It is not a second
   source of truth: the default is the URL, and `--check` in CI runs without it.
   ═══════════════════════════════════════════════════════════════════════════ */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const DEFAULT_SOURCE = "https://cdn.thinktalentws48.click/starterkit/colors_and_type.css";
const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const TARGET = join(ROOT, "styles.css");

const sourceArg = process.argv.find((arg) => arg.startsWith("--source="));
const SOURCE = sourceArg ? sourceArg.slice("--source=".length) : DEFAULT_SOURCE;
const isRemote = /^https?:\/\//.test(SOURCE);

const START = "/* @tokens:start — generated by scripts/sync-tokens.mjs, do not edit */";
const END = "/* @tokens:end */";

/* The sheet publishes its light scheme under MUI's attribute. */
const LIGHT_SELECTOR = '[data-mui-color-scheme="light"]';
const ALIAS = "--ic-t-";

/** Body of the first top-level `selector { … }`, by brace matching. */
function ruleBody(css, selector) {
  const at = css.indexOf(selector + " {");
  if (at === -1) throw new Error(`selector not found in token sheet: ${selector}`);
  const open = css.indexOf("{", at);
  let depth = 0;
  for (let i = open; i < css.length; i++) {
    if (css[i] === "{") depth++;
    else if (css[i] === "}" && --depth === 0) return css.slice(open + 1, i);
  }
  throw new Error(`unterminated rule: ${selector}`);
}

/** Custom properties only, in source order. Comments and `color-scheme:` dropped. */
function customProps(body) {
  const out = new Map();
  let depth = 0;
  let buf = "";
  const flush = () => {
    const decl = buf.replace(/\/\*[\s\S]*?\*\//g, "").trim();
    buf = "";
    const split = decl.indexOf(":");
    if (split === -1) return;
    const name = decl.slice(0, split).trim();
    if (name.startsWith("--")) out.set(name, decl.slice(split + 1).trim().replace(/\s+/g, " "));
  };
  for (const ch of body) {
    if (ch === "(") depth++;
    else if (ch === ")") depth--;
    if (ch === ";" && depth === 0) flush();
    else buf += ch;
  }
  flush();
  return out;
}

/**
 * Inline a vendored default for every var() inside a vendored value, so the
 * default stands on its own. `seen` breaks a cycle in the source sheet rather
 * than recursing forever.
 */
function selfContained(value, lookup, seen = new Set()) {
  return value.replace(/var\(\s*(--[\w-]+)\s*\)/g, (whole, name) => {
    if (seen.has(name)) return whole;
    const inner = lookup(name);
    if (inner === undefined) return whole;
    return `var(${name}, ${selfContained(inner, lookup, new Set([...seen, name]))})`;
  });
}

const sheet = isRemote
  ? await fetch(SOURCE).then((res) => {
      if (!res.ok) throw new Error(`${SOURCE} → HTTP ${res.status}`);
      return res.text();
    })
  : readFileSync(SOURCE, "utf8");

const dark = customProps(ruleBody(sheet, ":root"));
const light = customProps(ruleBody(sheet, LIGHT_SELECTOR));

const current = readFileSync(TARGET, "utf8");
const head = current.indexOf(START);
const tail = current.indexOf(END);
if (head === -1 || tail === -1) throw new Error("token markers missing from styles.css");

/* Seeds from the hand-written CSS only — the generated block is cut out first so
   an alias cannot keep itself alive by being referenced by its own siblings. */
const handWritten = current.slice(0, head) + current.slice(tail + END.length);
const used = new Set(
  [...new Set(handWritten.match(new RegExp(String.raw`${ALIAS}[\w-]+`, "g")) ?? [])].map(
    (alias) => "--" + alias.slice(ALIAS.length),
  ),
);

const missing = [...used].filter((name) => !dark.has(name));
if (missing.length) throw new Error(`consumed but absent from the token sheet: ${missing.join(", ")}`);

/* Emit in the sheet's own order — it groups by role (palette, text, borders,
   radii, channels), which reads better than alphabetical and is just as stable. */
const seeds = [...dark.keys()].filter((name) => used.has(name));

const darkOf = (name) => dark.get(name);
const lightOf = (name) => light.get(name) ?? dark.get(name);

const declare = (name, lookup, indent) =>
  `${indent}${ALIAS}${name.slice(2)}: var(${name}, ${selfContained(lookup(name), lookup)});`;

const darkBlock = seeds.map((name) => declare(name, darkOf, "  ")).join("\n");

/* A token earns a light declaration when its vendored default actually differs
   there — either it is redefined, or something it references is. */
const flipped = seeds.filter((name) => declare(name, darkOf, "") !== declare(name, lightOf, ""));

const lightBlock = (indent) => flipped.map((name) => declare(name, lightOf, indent)).join("\n");

const block = `${START}
/* Source: ${DEFAULT_SOURCE} — regenerate with \`pnpm sync:tokens\`.
   Each alias is \`var(<host token>, <vendored default>)\`: the host's sheet wins
   whenever it defines the token, these values render the card when it does
   not. Scoped to .ic-card — this file declares nothing on :root. */

.ic-card {
${darkBlock}
}

/* Light scheme. Surfaces invert and brand hues darken, so the channels flip with
   them: a gradient drawn in the dark-surface mint glows far too hot on white. */
${LIGHT_SELECTOR} .ic-card,
[data-theme="light"] .ic-card {
${lightBlock("  ")}
}

/* Same defaults for a host that ships no scheme attribute at all. Scoped to a
   root carrying neither: without that guard, a host running dark mode on a
   light-preference machine would pick these up. */
@media (prefers-color-scheme: light) {
  :root:not([data-mui-color-scheme]):not([data-theme]) .ic-card {
${lightBlock("    ")}
  }
}
${END}`;

const next = current.slice(0, head) + block + current.slice(tail + END.length);

if (process.argv.includes("--check")) {
  if (next !== current) {
    console.error("styles.css tokens are stale — run `pnpm sync:tokens`");
    process.exit(1);
  }
  console.log(`tokens up to date (${seeds.length} aliased, ${flipped.length} flip in light)`);
} else {
  writeFileSync(TARGET, next);
  console.log(`synced ${seeds.length} tokens from ${SOURCE} (${flipped.length} flip in light)`);
}
